#!/usr/bin/env bash
# ASTRA /uat-parallel — merge per-case JSON into index.html + issues.md + session.json
# Usage: uat-parallel-report.sh <SESSION_DIR> <REPORT_TEMPLATE_HTML>
set -euo pipefail

SESSION_DIR="${1:?SESSION_DIR required}"
TEMPLATE="${2:?TEMPLATE path required}"
RESULTS_DIR="$SESSION_DIR/raw/results"

if [ ! -d "$RESULTS_DIR" ]; then
  echo "[uat-parallel] No results in $RESULTS_DIR — nothing to merge." >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "[uat-parallel] node is required to merge results." >&2
  exit 2
fi

node - "$SESSION_DIR" "$TEMPLATE" "$RESULTS_DIR" <<'NODE'
const fs = require('fs');
const path = require('path');

const [SESSION_DIR, TEMPLATE, RESULTS_DIR] = process.argv.slice(2);

// i18n dictionary — embedded mirror of skills/user-test/references/i18n-strings.md.
// The SSoT file is documentation; the runtime values live here.
// Keep the two in sync when adding/changing strings.
// /uat-parallel uses M_ISSUES_REPORT_TITLE_PARALLEL (with "(parallel)" / "(병렬)"
// qualifier) instead of M_ISSUES_REPORT_TITLE, so a single glance at the header
// tells the reader whether the run was sequential (Chrome MCP) or parallel.
// M_DEV_HINT is intentionally absent here — the Playwright runner has no LLM
// in the loop to author per-failure hints.
const LANG = (() => {
  const raw = String(process.env.UAT_LANG || 'vi').toLowerCase();
  if (['vi', 'vie', 'vietnamese'].includes(raw)) return 'vi';
  if (['en', 'eng', 'english'].includes(raw)) return 'en';
  if (['ko', 'kor', 'korean'].includes(raw)) return 'ko';
  return 'vi';
})();

const I18N = {
  vi: {
    T_REPORT_TITLE: '📋 Báo cáo UAT',
    T_REPORT_SUBTITLE: 'Báo cáo kiểm thử người dùng cuối — Session',
    T_STARTED: '🕒 Bắt đầu',
    T_FINISHED: '🏁 Kết thúc',
    T_MODE: '⚙️ Chế độ',
    T_LABEL_TEST_CASES: 'Test Cases',
    T_LABEL_PASS: 'PASS',
    T_LABEL_FAIL: 'FAIL',
    T_LABEL_DURATION: 'Thời gian',
    T_HEADING_DETAILS: 'Chi tiết test cases',
    T_HEADING_ISSUES: 'Issues',
    T_EMPTY_NO_ISSUES: 'Không có lỗi nào trong session này.',
    T_SEE_DETAILS_AT: 'Xem chi tiết tại',
    T_ISSUES_WORD: 'lỗi',
    T_FOOTER_GENERATED: 'Sinh bởi ASTRA',
    T_STATUS_PASS: 'PASS',
    T_STATUS_FAIL: 'FAIL',
    T_STATUS_SKIPPED: 'SKIPPED',
    M_ISSUES_REPORT_TITLE_PARALLEL: '# Báo cáo UAT Issues (parallel)',
    M_SESSION: 'Session',
    M_CASES_RUN: 'Test Cases chạy',
    M_TOTAL_ISSUES: 'Tổng số lỗi',
    M_ISSUE: 'Issue',
    M_TEST_CASE: 'Test Case',
    M_STEP: 'Bước',
    M_EXPECTED: 'Expected',
    M_ACTUAL: 'Actual',
    M_SEVERITY_REASON: 'Lý do gán',
    M_SCREENSHOT: 'Screenshot',
    M_TRACE: 'Trace (Playwright)',
  },
  en: {
    T_REPORT_TITLE: '📋 UAT Report',
    T_REPORT_SUBTITLE: 'End-user acceptance test report — Session',
    T_STARTED: '🕒 Started',
    T_FINISHED: '🏁 Finished',
    T_MODE: '⚙️ Mode',
    T_LABEL_TEST_CASES: 'Test Cases',
    T_LABEL_PASS: 'PASS',
    T_LABEL_FAIL: 'FAIL',
    T_LABEL_DURATION: 'Duration',
    T_HEADING_DETAILS: 'Test case details',
    T_HEADING_ISSUES: 'Issues',
    T_EMPTY_NO_ISSUES: 'No issues found in this session.',
    T_SEE_DETAILS_AT: 'See details at',
    T_ISSUES_WORD: 'issues',
    T_FOOTER_GENERATED: 'Generated by ASTRA',
    T_STATUS_PASS: 'PASS',
    T_STATUS_FAIL: 'FAIL',
    T_STATUS_SKIPPED: 'SKIPPED',
    M_ISSUES_REPORT_TITLE_PARALLEL: '# UAT Issues Report (parallel)',
    M_SESSION: 'Session',
    M_CASES_RUN: 'Test cases run',
    M_TOTAL_ISSUES: 'Total issues',
    M_ISSUE: 'Issue',
    M_TEST_CASE: 'Test Case',
    M_STEP: 'Step',
    M_EXPECTED: 'Expected',
    M_ACTUAL: 'Actual',
    M_SEVERITY_REASON: 'Reason for',
    M_SCREENSHOT: 'Screenshot',
    M_TRACE: 'Trace (Playwright)',
  },
  ko: {
    T_REPORT_TITLE: '📋 UAT 보고서',
    T_REPORT_SUBTITLE: '최종 사용자 수용 테스트 보고서 — 세션',
    T_STARTED: '🕒 시작',
    T_FINISHED: '🏁 종료',
    T_MODE: '⚙️ 모드',
    T_LABEL_TEST_CASES: '테스트 케이스',
    T_LABEL_PASS: 'PASS',
    T_LABEL_FAIL: 'FAIL',
    T_LABEL_DURATION: '소요 시간',
    T_HEADING_DETAILS: '테스트 케이스 상세',
    T_HEADING_ISSUES: '이슈',
    T_EMPTY_NO_ISSUES: '이 세션에서 발견된 이슈가 없습니다.',
    T_SEE_DETAILS_AT: '자세한 내용은 다음에서 확인하세요',
    T_ISSUES_WORD: '건의 이슈',
    T_FOOTER_GENERATED: 'ASTRA로 생성됨',
    T_STATUS_PASS: '통과',
    T_STATUS_FAIL: '실패',
    T_STATUS_SKIPPED: '건너뜀',
    M_ISSUES_REPORT_TITLE_PARALLEL: '# UAT 이슈 리포트 (병렬)',
    M_SESSION: '세션',
    M_CASES_RUN: '실행된 테스트 케이스',
    M_TOTAL_ISSUES: '전체 이슈 수',
    M_ISSUE: '이슈',
    M_TEST_CASE: '테스트 케이스',
    M_STEP: '단계',
    M_EXPECTED: '기대값',
    M_ACTUAL: '실제값',
    M_SEVERITY_REASON: '사유',
    M_SCREENSHOT: '스크린샷',
    M_TRACE: 'Trace (Playwright)',
  },
};
const T = I18N[LANG];

// 1. Load all per-case results
const cases = fs
  .readdirSync(RESULTS_DIR)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => JSON.parse(fs.readFileSync(path.join(RESULTS_DIR, f), 'utf8')));

if (cases.length === 0) {
  console.error('[uat-parallel] No case results found.');
  process.exit(0);
}

// 2. Aggregate
const startedAt = cases.map((c) => c.started_at).sort()[0];
const finishedAt = cases.map((c) => c.finished_at).sort().slice(-1)[0];
const passCount = cases.filter((c) => c.status === 'pass').length;
const failCount = cases.filter((c) => c.status === 'fail').length;
const durationMs = new Date(finishedAt).getTime() - new Date(startedAt).getTime();
const sessionId = path.basename(SESSION_DIR.replace(/\/$/, ''));

const sevCount = { critical: 0, high: 0, medium: 0, low: 0 };
const issues = [];
for (const c of cases) {
  if (c.status !== 'fail' || !c.first_failure) continue;
  const sev = c.first_failure.severity || 'low';
  sevCount[sev] = (sevCount[sev] || 0) + 1;
  issues.push({
    case_id: c.id,
    case_name: c.name,
    step_num: c.first_failure.step?.num ?? '?',
    step_total: c.steps.length,
    step_name: c.first_failure.step?.name ?? '(action error)',
    severity: sev,
    reason: c.first_failure.reason,
    expected: c.first_failure.assertion?.text || c.first_failure.step?.action_error || '',
    actual: c.first_failure.assertion?.actual || c.first_failure.step?.action_error || '',
    screenshot: c.first_failure.step?.screenshot || '',
    trace_hint: `npx playwright show-trace ./traces/${c.id}.zip`,
  });
}

// 3. Render HTML cases
function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderCase(c) {
  const stepsHtml = c.steps
    .map((s) => {
      const cls = s.status === 'fail' ? 'fail' : '';
      const asserts = (s.assertions || [])
        .map((a) => `<li class="${a.ok ? 'ok' : 'ng'}">${esc(a.text)}${!a.ok && a.actual ? ` <code>(actual: ${esc(a.actual).slice(0, 80)})</code>` : ''}</li>`)
        .join('');
      const sevBadge =
        s.status === 'fail' && c.first_failure
          ? `<span class="severity ${c.first_failure.severity}">${c.first_failure.severity.toUpperCase()}</span>`
          : '';
      const shot = s.screenshot ? `<div class="thumb"><a href="./${s.screenshot}" target="_blank"><img src="./${s.screenshot}" alt="step ${s.num}"></a></div>` : '';
      return `
      <div class="step ${cls}">
        <div class="num">${s.num}</div>
        <div class="body">
          <div class="title">${esc(s.name)}${sevBadge}</div>
          <div class="action">${esc(s.action)}</div>
          <div class="asserts"><ul>${asserts || '<li class="ok">(no assertions)</li>'}</ul></div>
        </div>
        ${shot}
      </div>`;
    })
    .join('');
  const statusClass = c.status === 'pass'
    ? 'pass'
    : c.status === 'skipped'
      ? 'skipped'
      : 'fail';
  const statusLabel = c.status === 'pass'
    ? T.T_STATUS_PASS
    : c.status === 'skipped'
      ? T.T_STATUS_SKIPPED
      : T.T_STATUS_FAIL;
  return `
  <div class="tc">
    <div class="tc-head">
      <div><span class="id">${esc(c.id)}</span><span class="name">${esc(c.name)}</span></div>
      <span class="tc-status ${statusClass}">${esc(statusLabel)}</span>
    </div>
    <div class="steps">${stepsHtml}</div>
  </div>`;
}

const testCasesHtml = cases.map(renderCase).join('\n');

const issuesHtml =
  failCount === 0
    ? `<div class="empty"><div class="icon">🎉</div>${esc(T.T_EMPTY_NO_ISSUES)}</div>`
    : `<p>${esc(T.T_SEE_DETAILS_AT)} <a href="./issues.md">issues.md</a> (${failCount} ${esc(T.T_ISSUES_WORD)}: ${sevCount.critical} CRITICAL, ${sevCount.high} HIGH, ${sevCount.medium} MEDIUM, ${sevCount.low} LOW)</p>`;

// 4. Render HTML report
const tpl = fs.readFileSync(TEMPLATE, 'utf8');
let html = tpl
  .replace(/\{\{LANG\}\}/g, LANG)
  .replace(/\{\{SESSION_ID\}\}/g, sessionId)
  .replace(/\{\{STARTED_AT\}\}/g, startedAt)
  .replace(/\{\{FINISHED_AT\}\}/g, finishedAt)
  .replace(/\{\{MODE\}\}/g, `auto-parallel (${process.env.UAT_WORKERS || '?'} workers)`)
  .replace(/\{\{TOTAL_CASES\}\}/g, String(cases.length))
  .replace(/\{\{PASS_COUNT\}\}/g, String(passCount))
  .replace(/\{\{FAIL_COUNT\}\}/g, String(failCount))
  .replace(/\{\{DURATION\}\}/g, `${(durationMs / 1000).toFixed(1)}s`)
  .replace(/\{\{TEST_CASES_HTML\}\}/g, testCasesHtml)
  .replace(/\{\{ISSUES_HTML\}\}/g, issuesHtml);

// i18n placeholders {{T_*}} → values from the chosen language
for (const [key, val] of Object.entries(T)) {
  if (!key.startsWith('T_')) continue;
  html = html.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), val);
}

fs.writeFileSync(path.join(SESSION_DIR, 'index.html'), html);

// 5. Render issues.md
if (failCount > 0) {
  const lines = [
    T.M_ISSUES_REPORT_TITLE_PARALLEL,
    `**${T.M_SESSION}**: ${sessionId}`,
    `**${T.M_CASES_RUN}**: ${cases.length}`,
    `**${T.M_TOTAL_ISSUES}**: ${failCount} (${sevCount.critical} CRITICAL, ${sevCount.high} HIGH, ${sevCount.medium} MEDIUM, ${sevCount.low} LOW)`,
    ``,
    `---`,
    ``,
  ];
  issues.forEach((iss, idx) => {
    lines.push(`## ${T.M_ISSUE} #${idx + 1} — ${iss.severity.toUpperCase()}`);
    lines.push(`**${T.M_TEST_CASE}**: ${iss.case_id} - ${iss.case_name}`);
    lines.push(`**${T.M_STEP}**: ${iss.step_num}/${iss.step_total} — ${iss.step_name}`);
    lines.push(``);
    lines.push(`### ${T.M_EXPECTED}`);
    lines.push(`- ${iss.expected || '(action execution)'}`);
    lines.push(``);
    lines.push(`### ${T.M_ACTUAL}`);
    lines.push(`- ${iss.actual || '(no detail)'}`);
    lines.push(``);
    lines.push(`### ${T.M_SEVERITY_REASON} ${iss.severity.toUpperCase()}`);
    lines.push(iss.reason || '(no rationale)');
    lines.push(``);
    if (iss.screenshot) {
      lines.push(`### ${T.M_SCREENSHOT}`);
      lines.push(`![${iss.case_id} step ${iss.step_num}](./${iss.screenshot})`);
      lines.push(``);
    }
    lines.push(`### ${T.M_TRACE}`);
    lines.push('```bash');
    lines.push(iss.trace_hint);
    lines.push('```');
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  });
  fs.writeFileSync(path.join(SESSION_DIR, 'issues.md'), lines.join('\n'));
}

// 6. Consolidated session.json
const session = {
  session_id: sessionId,
  mode: 'auto-parallel',
  lang: LANG,
  started_at: startedAt,
  finished_at: finishedAt,
  duration_ms: durationMs,
  summary: {
    total: cases.length,
    pass: passCount,
    fail: failCount,
    severity: sevCount,
  },
  cases: cases.map((c) => ({
    id: c.id,
    name: c.name,
    status: c.status,
    duration_ms: c.duration_ms,
    worker_index: c.worker_index,
  })),
  issues,
};
fs.writeFileSync(path.join(SESSION_DIR, 'session.json'), JSON.stringify(session, null, 2));

// 7. Cleanup raw/ on success
fs.rmSync(path.join(SESSION_DIR, 'raw'), { recursive: true, force: true });

console.log(`[uat-parallel] Merged ${cases.length} cases → ${SESSION_DIR}/index.html`);
NODE
